name: hello-world

on: push

jobs:
 hello-world-job:

   runs-on: ubantu-latest

   steps:
     - name: check out repository code
       uses: action/checkout@v4
     - run: echo "(cat hello_world.txt)"
